baseURL = "https://aoi0701.github.io/blog-ca-nhan/"
languageCode = "vi"
title = "HÀNH TRÌNH TUỔI SINH VIÊN"
theme = "PaperMod"

# ===== MENU CHÍNH =====
[menu]

  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 2

  [[menu.main]]
    name = "Nhật ký SV "
    url = "/nhat-ky-sinh-vien/"
    weight = 3

  [[menu.main]]
    name = "Góc nhìn"
    url = "/goc-nhin/"
    weight = 4





  [[menu.main]]
    name = "About Me"
    url = "/about/"
    weight = 5

[params]
  #  QUAN TRỌNG: tắt list post ở Home
    customCSS = ["css/extended/custom.css"]
  mainSections = []

 [params.profileMode]
enabled = false


      
    
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


